daos-stack/packaging

Jenkinsfile
Makefile_packaging.mk
docker/Dockerfile.leap.15

Signed-off-by: John.E.Malmberg <john.e.malmberg@intel.com>

CORCI-725 build: Add Leap-15 builds

---

Makefile
Makefile_packaging.mk

Remove extra repos from per distro standard sets.  Projects should add
those as required.
Small tidy-ups.

Add support for adding el7_REPOS; reduce base repos

---

Makefile_packaging.mk

Should do fatal checks before warning checks

---

Makefile_packaging.mk

Update to support using for buiding raft.

CORCI-668 build: Update to support raft

---

Makefile_packaging.mk
install

Use proper distro name in repo URLs

---

Dockerfile.mockbuild

Due to https://github.com/rpm-software-management/mock/issues/484.

Revert opensuse-leap-15.1 .tpl renaming (#1936)

---

Makefile_distro_vars.mk
Makefile_packaging.mk

Add support for sig files for file signatures.
Fix locale handling.

CORCI-881 build: Support sig files and locale fix.

---

Makefile_distro_vars.mk
Makefile_packaging.mk

Make spectool definable per distro.
Allow a job to add a repo.

Allow PRs to request using other PRs

---

Makefile_packaging.mk

Add PR-repos-{el7,leap15}

---

Makefile_packaging.mk

Fix spelling mistake

---

Makefile_packaging.mk

Handle Sources with # in them

---

Dockerfile.mockbuild
Makefile_distro_vars.mk
Makefile_packaging.mk

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

CORCI 983: Update packaging for Suse 15.2

---

Makefile_packaging.mk
install

Handle spec files with multiple Sources

---

Makefile_packaging.mk

So that values return there have properly expanded macros.

Pass --defines to spectool

---

Makefile_packaging.mk

RPM macro definitions don't specify the %

---

Makefile_packaging.mk

Add more show_* targets

---

Makefile_packaging.mk
rpm_chrootbuild

Also, use spectool to download sources to support multiple sources.
Exclude utils dir from packaging_check diff.

Add EL8 support

---

Dockerfile.ubuntu.20.04

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

Add dh-python to ubuntu Dockerfile

---

Makefile_packaging.mk

Use dnf in Makefile_packaging.mk
Signed-off-by: Danielle Sikich <danielle.sikich@intel.com>

use dnf instead of yum

---

rpm_chrootbuild

New names for CentOS 8.x and Opensuse leap 15.x artifact directories.

CORCI-1103 Build: Fix PR_REPO handling

---

Dockerfile.centos.7
Dockerfile.coverity
Dockerfile.mockbuild
Jenkinsfile

CORCI-1103 Build: Update copyright dates

---

Jenkinsfile
Makefile
Makefile_distro_vars.mk
Makefile_packaging.mk
rpm_chrootbuild

They aren't really necessary as we have a completely different path to
supporting DAOS on both 8.3 and 8.4.

Revert changes to build on EL 8.3 and 8.4

---

README.md

Clarify comment about submodule use

---

Dockerfile.mockbuild
Jenkinsfile
Makefile_distro_vars.mk
Makefile_packaging.mk

DAOS-9797 packaging: Use generic EL

---

Dockerfile.mockbuild
Jenkinsfile
Makefile_distro_vars.mk
Makefile_packaging.mk

Fix being able to specify EL8 release with AppStream and PowerTools repos.

Allow projects to specify their EL8 point release

---

Makefile_packaging.mk
rpm_chrootbuild

Also, test for any *epel-8-x86_64 combo.

Only use $(DISTRO_BASE)_LOCAL_REPOS on debian

---

Dockerfile.mockbuild
Jenkinsfile
Makefile_distro_vars.mk
Makefile_packaging.mk
rpm_chrootbuild

Install Artifactory repos for RPM testing when building dependencies
with packageBuildingPipeline().

Updates for Leap 15.5

---

Dockerfile.mockbuild
Makefile_packaging.mk
ccache-stats.patch
get_base_branch
rpm_chrootbuild

To get some speedup in re-building packages.

Add mock ccache patch and get_base_branch

---

Dockerfile.ubuntu.20.04
LICENSE
SECURITY.md
install

Also resolve OpenSSF LICENSE and SECURITY issues.

Use HPE repo key from Artifactory
