daos-stack/packaging

Dockerfile.centos.7
Dockerfile.leap.15
Dockerfile.leap.42.3
Dockerfile.sles.12.3
Jenkinsfile
Makefile
Makefile_packaging.mk
libfabric.spec

things I think.
Enhancements:
- short-circuits out of potential distracting non-error errors in artifact collection
- simplifies dockerfiles greatly
- makes the suse ones almost identical
- tempting to even autogenerate them from a single template.
- puts simplified package dependency <dep>[@branch[:build_number]] specification into the Makefile
- consistent for suse and centos
- gives all repos to be used to build with --repo command
- no assumptions/requirements on host repos
- which means the build command is more portable to other environments
- no needing to refresh repos in the host environment for build

Some enhancements to the existing work to simplify

---

Dockerfile.centos.7
Makefile_packaging.mk

Allow the caller to specify rpmbuild options.
Add python-srpm-macros to the CentOS 7 Dockerfile so that
linting specfiles that have python2/3 build support will find
the necessary macros.

Caller rpmbuild options; python-srpm-macros

---

Dockerfile.leap.15
Makefile_packaging.mk

By way of a "test:" target in the project Makefile.
- runs as root in a docker container
- provide helpers to installs project specified additional repos
Also support for per-distro additional repos.
Provide a default JENKINS_URL for when used outside of Jenkins.
Add gpg keys for specified additional repos on SUSE distros.

Add ability to run tests

---

Makefile_packaging.mk

Fix Ubuntu to always detar the original source tarball.
Add SLES and CentOS group repositories to help insulate us from
external mirror network issues.

CORCI-784 build: Group repos and Ubuntu fix

---

Makefile
Makefile_packaging.mk

Found another hidden directory to clean up for Ubuntu builds.
Should only be present in workspaces used for non chroot builds.
When a REPOSITORY server like NEXUS is configured to proxy for public
RPM repositories, don't also add them to the repository list.

CORCI-784 build: Fix for Ubuntu builds

---

Makefile_packaging.mk

Fix usage of DISTRO_BASE to be consistent.

CORCI-784 build: Consistent use of DISTRO_BASE

---

Makefile_packaging.mk

Add support for CentOS 8 mockbuilds.

DCO-8741 build: Update for CentOS 8

---

Dockerfile.coverity

Add a Coverity dockerfile, Use dnf for Mockbuild.

CORCI-752 build: Add Coverity dockerfile

---

Makefile_packaging.mk

To sub-commands used to determine variable values so that they determine
the correct value for the target build platform.

Pass the CHROOT_NAME environment variable through

---

Makefile_packaging.mk

To be before the include of packaging/Makefile_distro_vars.mk as that file
references that variable.

Need to move the default CHROOT_NAME assignment

---

Dockerfile.mockbuild

Since the 2.0 release for leap 15.1 building was a nightmare.

Pin mock and mock-core-configs to the 1.x version

---

install

Another thing copied that is not actually needed in the target.

Remove packaging/packaging in install

---

Makefile_packaging.mk

Adding a default test case to verify that the built RPM can be
installed.
Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

CORCI-938 build: Adding default test case.

---

Makefile_packaging.mk

Allow the Makefile to define test RPMs

---

debian_chrootbuild

For when simply building the package is good enough, as in when building
a package  is just a test for correctness such as in pipeline-lib.

Allow the caller to override the DPKG_GENSYMBOLS_CHECK_LEVEL

---

Makefile_packaging.mk

The repositories passed for testing are now a | delimited list.

CORCI-985 Build: Fix repository testing

---

rpm_chrootbuild

This changes the packaging procedure to always require that a local
repository has been setup to cache the upstream repositories for
the OpenSUSE Leap-15 distros.
This is to guard against intermittent upstream issues.

CORCI-1036 Build: Always use local repository

---

Makefile_packaging.mk

In RPM, pre-release tags are identified in versions with a ~.  These are
not typically in the actual upstream version.
So remove them when constructing the $(DL_VERSION).
Skip-PR-comments: true

Remove ~ from DL_VERSION

---

Dockerfile.mockbuild
Makefile_distro_vars.mk
Makefile_packaging.mk
rpm_chrootbuild

Allow use of local repository mirrors when available for RPM building.

DAOS-7813 Build: Use local repo mirrors

---

Dockerfile.centos.7

Installing dnf allows other builds to use dnf instead of yum.
Signed-off-by: Danielle Sikich <danielle.sikich@intel.com>

install dnf

---

Jenkinsfile
Makefile
Makefile_distro_vars.mk
Makefile_packaging.mk
rpm_chrootbuild

Add CentOS 8.4 and Leap 15.3 to the builds.
Set up the builds to support multiple dot versions for CentOS 8 and Leap
15.

CORCI-1103 build: Add CentOS 8.4, Leap 15.3

---

Dockerfile.mockbuild
Jenkinsfile
Makefile
Makefile_distro_vars.mk
Makefile_packaging.mk
rpm_chrootbuild

Also, stop using group repos and add a temporary hack to use proxy repos
directly.
Improve building packages from git commit hashes that preserves the
base-verison + patch paradigm.
Add a cachebust to the mock build Dockerfile to ensure that the mock
host is up-to-date.
Add support for the <distro>-version commit pragma.

DAOS-8915: Leap 15 builds should be on 15.3

---

Dockerfile.mockbuild

As the update replaces epel-8-* configs with <distro>+epel-8-* which we are not ready for yet.

CORCI-1176 build: Hold back mock-core-configs

---

Makefile_packaging.mk

Signed-off-by: David Quigley <david.quigley@intel.com>

Add missing make target rule for go binary downloads.

---

Dockerfile.ubuntu.20.04

PMDK needs it for dh_auto_clean before chroot is built
Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

DAOS-11151 build: Add cmake to Ubuntu default

---

Dockerfile.ubuntu.20.04

I've mentioned this to pmdk but it fails to clean if it's not
installed so I added it to to packaging script.
Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

DAOS-11151 pmdk: Need valgrind for pmdk build

---

Dockerfile.mockbuild

Also move the patching to after the dnf upgrade so that the dnf upgrade
doesn't wipe out the patching.

Only patch rpmlint if necessary

---

Dockerfile.mockbuild
Dockerfile.ubuntu.20.04
Jenkinsfile
Makefile_distro_vars.mk
Makefile_packaging.mk
debian_chrootbuild
install
rpm_chrootbuild

If multiple pragmas reference a repo, only add the first one.  By this
measure, PR-Repos-$distro should be specified before PR-Repos.
Default mock buiding to Fedora 38 but allow override for, say Leap 15.4
that can only build on mock on Fedora 37.
Updated Ubuntu buid environment packages.
Save and restore mock root_cache tarballs to speed up builds.
Simplify mock configuration file build and use.
Skip-PR-comments: true

Add support for EL9

---

get_base_branch

The githooks support DAOS_ORIGIN setting to change default. This will be passed as ORIGIN to this script so only set to origin if it's not set.

DAOS-16744 ci: Enable change of origin
